apiVersion: v1
kind: Pod
metadata:
  name: curl-test-pod
  namespace: foo
  labels:
    app: curl-test-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:8.2.1
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
