meshConfig:
  accessLogFile: /dev/stdout
  extensionProviders:
  - name: "ext-authz-http"
    envoyExtAuthzHttp:
      service: "ext-authz.foo.svc.cluster.local"
      port: 8000
      includeRequestHeadersInCheck: ["authorization", "cookie", "x-ext-authz", "x-msisdn"]
      headersToUpstreamOnAllow: ["x-auth-user", "x-auth-email"]
      headersToDownstreamOnDeny: ["content-type", "x-auth-reason"]
  - name: "ext-authz-grpc"
    envoyExtAuthzGrpc:
      service: "ext-authz.foo.svc.cluster.local"
      port: 9000
